/* This file is generated by BUSMASTER */
/* VERSION [1.1] */
/* BUSMASTER VERSION [2.3.0] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>
#include "\\192.168.1.234\avr\CanDisplay\info\haltech_broadcast_can_v2_0_Unions.h"

/* End BUSMASTER include header */


/* Start BUSMASTER global variable */
Eng1 sMsgStruct = { 0x360, 1, 0, 8, 1, { 0, 0, 0, 0, 0, 0, 0, 0 },1 };
/* End BUSMASTER global variable */


/* Start BUSMASTER Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnTimer_sendFrame_20( );
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER generated function - OnTimer_sendFrame_20 */
void OnTimer_sendFrame_20( )
{
// send out message
SendMsg (&sMsgStruct);

// increase RPM value by 10 till 8000 then flip to zero
if(sMsgStruct.m_sWhichBit.RPM < 8000) sMsgStruct.m_sWhichBit.RPM += 10;
else sMsgStruct.m_sWhichBit.RPM = 0;
}/* End BUSMASTER generated function - OnTimer_sendFrame_20 */
